repos:
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.18.2 # Usa la última versión estable o la que prefieras
  hooks:
    - id: gitleaks
      args: [
        "--report-format=json",
        "--report-path=gitleaks-report.json"
      ]
