name: 51 Scan Docker Image
on:
  workflow_dispatch:
  workflow_call:
env:
  REGISTRY: jotamariodev

jobs:
  container-image-scan:
    name: Container Image Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get image name and version from package.json
        id: pkg
        run: |
          echo "FRONTEND_IMAGE=$(jq -r .name frontend/package.json)" >> $GITHUB_ENV
          echo "FRONTEND_VERSION=$(jq -r .version frontend/package.json)" >> $GITHUB_ENV
      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull Docker image
        run: docker pull ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE}}:${{ env.FRONTEND_VERSION }}
        id: pull-image

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE}}:${{ env.FRONTEND_VERSION }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

      # --- Snyk Container Scan ---
      - name: Install Snyk CLI
        uses: snyk/actions/setup@master
        env:
          SNYK_TOKEN: ${{ secrets.OUR_SNYK_KEY }} 

      - name: Snyk Authenticate
        run: snyk auth ${{ secrets.OUR_SNYK_KEY }}

      - name: Snyk Container monitor
        run: snyk container monitor ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE}}:${{ env.FRONTEND_VERSION }} --file=Dockerfile
        working-directory: ./frontend

      - name: Run Snyk to check for vulnerabilities in the Docker image
        uses: snyk/actions/docker@master
        with:
          image: ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE }}:${{ env.FRONTEND_VERSION }}
          args: --file=frontend/Dockerfile --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.OUR_SNYK_KEY }}
        continue-on-error: true

      - name: Upload Snyk scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'snyk.sarif'