name: 50 Build docker image

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      image-tag:
        description: 'The image tag of the new docker image'
        value: ${{ jobs.docker.outputs.image-tag }}

    
env:
  REGISTRY: jotamariodev
  IMAGE_NAME: ${{ github.repository }}


jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read 
      security-events: write 
      actions: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Get image name and version from package.json
      id: pkg
      run: |
        echo "FRONTEND_IMAGE=$(jq -r .name frontend/package.json)" >> $GITHUB_ENV
        echo "FRONTEND_VERSION=$(jq -r .version frontend/package.json)" >> $GITHUB_ENV
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Dockerhub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push frontend Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE}}:${{ env.FRONTEND_VERSION }}
    
    - name: Image digest
      run: echo ${{ steps.build-and-publish.outputs.digest }}