name: 00 - Schedule Main CI / CD pipeline
on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  security-events: write
  checks: write
  issues: read
  pull-requests: write
  packages: write

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit # Inherits secrets from the calling workflow to the reusable workflow. See: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idsecretsinherit

  sca:
    needs: build
    name : Static Code Analysis
    uses: ./.github/workflows/sca.yml
    secrets: inherit

  sast:
    needs: build
    name: Static Application Security Testing
    uses: ./.github/workflows/sast.yml
    secrets: inherit

  docker:
    needs: [sca, sast]
    name: Build docker image
    uses: ./.github/workflows/docker.yml
    secrets: inherit

  container-image-scan:
    needs: docker
    name: Build docker image
    uses: ./.github/workflows/container-image-scan.yml
    secrets: inherit

