name: Main CI / CD pipeline
on:
  push:
    branches: ["main"]
    paths-ignore:
      - "**/*.md" # Ignore documentation changes to avoid triggering the pipeline unnecessarily
      - "**/*.txt"
  workflow_dispatch:

permissions:
  checks: write
  issues: read
  pull-requests: write
  contents: read

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit # Inherits secrets from the calling workflow to the reusable workflow. See: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idsecretsinherit

  sca:
    needs: build
    name : Static Code Analysis
    uses: ./.github/workflows/sca.yml
    secrets: inherit
