name: 20 SCA

on:
  workflow_dispatch:
  workflow_call:

jobs:
  sca:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@master
      - name: Download node_modules artifact
        uses: actions/download-artifact@v4
        with:
          name: node-modules
          path: ./frontend/node_modules
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.OUR_SNYK_KEY }}
      - name: Install Snyk CLI
        uses: snyk/actions/setup@master
        env:
          SNYK_TOKEN: ${{ secrets.OUR_SNYK_KEY }}  
         
      - name: Snyk Authenticate   
        run: snyk auth ${{ secrets.OUR_SNYK_KEY }}

      - name: Snyk Code Test
        run: snyk code test --all-projects
        continue-on-error: true
