name: 20 SCA

on:
  workflow_dispatch:
  workflow_call:

jobs:
  sca:
    permissions:
      contents: read
      security-events: write
      
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@master
      - name: Download node_modules artifact
        uses: actions/download-artifact@v4
        with:
          name: node-modules
          path: ./frontend/node_modules
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.OUR_SNYK_KEY }}
      - name: Install Snyk CLI
        uses: snyk/actions/setup@master
        env:
          SNYK_TOKEN: ${{ secrets.OUR_SNYK_KEY }}  
         
      - name: Snyk Authenticate   
        run: snyk auth ${{ secrets.OUR_SNYK_KEY }}

      - name: Snyk Code Test
        run: snyk test --all-projects --sarif > snyk.sarif || true
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.OUR_SNYK_KEY }}
      - name: Upload Snyk SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./frontend/snyk.sarif
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'test'
          path: '.'
          format: 'HTML'
          out: 'reports' # this is the default, no need to specify unless you wish to override it
          args: >
            --failOnCVSS 7
            --enableRetired
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ./frontend/reports
